// Verification-only. This package is M0's executable specification, not production
// infrastructure. It must never be imported by internal/kernel (D-023) and is frozen
// at the close of M0 (O1).
package m0

import (
	"fmt"
	"sort"
	"strings"
)

// VolatileBegin and VolatileEnd fence everything that legitimately differs between
// two runs. D-024 made determinism an acceptance criterion, so the strip performed by
// scripts/m0_accept.sh must be exact — a line-count heuristic is not good enough.
const (
	VolatileBegin = "<!-- volatile:begin -->"
	VolatileEnd   = "<!-- volatile:end -->"
)

// Header carries the volatile facts. Nothing here may appear below VolatileEnd.
type Header struct {
	GeneratedAt string
	Host        string
	DSN         string
	SchemaPath  string
}

// Render produces the transcript. Everything below VolatileEnd is required to be
// byte-identical across two clean runs when showTimings is false (probe E1).
func Render(h Header, probes []Probe, showTimings bool) string {
	sorted := make([]Probe, len(probes))
	copy(sorted, probes)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var b strings.Builder

	b.WriteString("# M0 Verification Transcript\n\n")
	b.WriteString("Milestone M0 — cluster + schema up. Generated by `cmd/m0verify`.\n")
	b.WriteString("Every row is a receipt: SQLSTATE from `*pgconn.PgError`, never a substring match.\n\n")

	b.WriteString(VolatileBegin + "\n\n")
	b.WriteString("| run fact | value |\n|---|---|\n")
	b.WriteString("| generated_at | " + h.GeneratedAt + " |\n")
	b.WriteString("| host | " + h.Host + " |\n")
	b.WriteString("| dsn | " + h.DSN + " |\n")
	b.WriteString("| schema | " + h.SchemaPath + " |\n\n")
	b.WriteString(VolatileEnd + "\n\n")

	passed, failed := tally(sorted)
	b.WriteString("## Verdict\n\n")
	if failed == 0 {
		b.WriteString(fmt.Sprintf("**M0 GREEN** — %d/%d probes passed.\n\n", passed, passed+failed))
	} else {
		b.WriteString(fmt.Sprintf("**M0 BLOCKED** — %d passed, %d failed.\n\n", passed, failed))
	}

	b.WriteString("## Probes\n\n")
	if showTimings {
		b.WriteString("| id | status | criterion | expected | observed | sqlstate | constraint | elapsed_ms |\n")
		b.WriteString("|---|---|---|---|---|---|---|---|\n")
	} else {
		b.WriteString("| id | status | criterion | expected | observed | sqlstate | constraint |\n")
		b.WriteString("|---|---|---|---|---|---|---|\n")
	}
	for _, p := range sorted {
		row := []string{
			p.ID,
			statusText(p.Pass),
			cell(p.Criterion),
			cell(p.Expected),
			cell(p.Observed),
			dash(p.SQLState),
			dash(p.Constraint),
		}
		if showTimings {
			row = append(row, fmt.Sprintf("%d", p.Elapsed.Milliseconds()))
		}
		b.WriteString("| " + strings.Join(row, " | ") + " |\n")
	}
	b.WriteString("\n")

	b.WriteString("## Statements\n\n")
	for _, p := range sorted {
		b.WriteString("**" + p.ID + "** — `" + p.Statement + "`\n\n")
	}

	b.WriteString("## Details\n\n")
	any := false
	for _, p := range sorted {
		if p.Detail == "" {
			continue
		}
		any = true
		b.WriteString("### " + p.ID + "\n\n" + p.Detail + "\n\n")
	}
	if !any {
		b.WriteString("_No probe produced detail output._\n\n")
	}

	return b.String()
}

// StripVolatile removes everything through VolatileEnd. Used by the determinism
// check and available to any consumer that needs the reproducible portion.
func StripVolatile(transcript string) string {
	idx := strings.Index(transcript, VolatileEnd)
	if idx < 0 {
		return transcript
	}
	return transcript[idx+len(VolatileEnd):]
}

func tally(probes []Probe) (passed, failed int) {
	for _, p := range probes {
		if p.Pass {
			passed++
		} else {
			failed++
		}
	}
	return passed, failed
}

func statusText(pass bool) string {
	if pass {
		return "PASS"
	}
	return "**FAIL**"
}

func cell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	return strings.TrimSpace(strings.ReplaceAll(s, "\n", " "))
}

func dash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
